
name: Machinefile build
run-name: building machinefile

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  build:
    name: build-process
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          make cross

      - name: Run test with action
        uses: gbraad-actions/machinefile-executor-action@main
        with:
          containerfile: 'test/Containerfile'
          context: 'test'
          arguments: --arg=USER=runner
          binarypath: ${{ github.workspace}}/out/linux-amd64/machinefile
